### ISSUE TITLE
SSL Cert not vaild for your domain

### ISSUE THREAD

**Issue by iamzubin** [AashvikTyagi/AashvikTyagi.github.io#1]
![image](https://github.com/user-attachments/assets/9179825c-ddc1-4446-bece-8ab571e43c70)

looks like Custom domain on github is not properly set.
maybe you missed this checkbox.
    Go to your GitHub repository's page.
    Click on the "Settings" tab.
    Scroll down to the "GitHub Pages" section.
    Click on the "Enforce HTTPS" checkbox.

**Comment by aashvikt** [comment]
ight i'll set up ssl soon

**Comment by aashvikt** [comment]
fixed!
